// server/services/github.service.js

const { Octokit } = require('@octokit/rest');
const fs = require('fs').promises;
const path = require('path');
const archiver = require('archiver');

class GitHubService {
  constructor() {
    this.clientId = process.env.GITHUB_CLIENT_ID;
    this.clientSecret = process.env.GITHUB_CLIENT_SECRET;
    this.redirectUri = process.env.GITHUB_REDIRECT_URI;
  }

  /**
   * Generate GitHub OAuth authorization URL
   * @param {string} state - State parameter for security
   * @returns {string} Authorization URL
   */
  getAuthUrl(state) {
    const scopes = 'repo,user:email';
    return `https://github.com/login/oauth/authorize?client_id=${this.clientId}&redirect_uri=${encodeURIComponent(this.redirectUri)}&scope=${scopes}&state=${state}`;
  }

  /**
   * Exchange authorization code for access token
   * @param {string} code - Authorization code from GitHub
   * @returns {Promise<string>} Access token
   */
  async getAccessToken(code) {
    const response = await fetch('https://github.com/login/oauth/access_token', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        client_id: this.clientId,
        client_secret: this.clientSecret,
        code,
        redirect_uri: this.redirectUri,
      }),
    });

    const data = await response.json();
    
    if (data.error) {
      throw new Error(`GitHub OAuth error: ${data.error_description}`);
    }

    return data.access_token;
  }

  /**
   * Get GitHub user information
   * @param {string} accessToken - GitHub access token
   * @returns {Promise<Object>} User information
   */
  async getUserInfo(accessToken) {
    const octokit = new Octokit({ auth: accessToken });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    return user;
  }

  /**
   * Create a new repository for the user
   * @param {string} accessToken - GitHub access token
   * @param {string} repoName - Repository name
   * @param {string} description - Repository description
   * @returns {Promise<Object>} Repository information
   */
  async createRepository(accessToken, repoName, description = 'Portfolio website generated by Portfolio Portal') {
    const octokit = new Octokit({ auth: accessToken });
    
    try {
      const { data: user } = await octokit.rest.users.getAuthenticated();
      const owner = user.login;
      
      // First check if repository already exists
      try {
        const { data: existingRepo } = await octokit.rest.repos.get({
          owner: user.login,
          repo: repoName,
        });
        console.log(`Repository already exists: ${existingRepo.full_name}`);
        
        // Check if repository is properly initialized by trying to get the main branch
        try {
          await octokit.rest.git.getRef({
            owner: user.login,
            repo: repoName,
            ref: 'heads/main',
          });
          console.log('Repository is properly initialized with main branch');
          return existingRepo;
        } catch (refError) {
          if (refError.status === 404) {
            console.log('Repository exists but has no main branch, will recreate');
            // Delete the existing repository and create a new one
            await octokit.rest.repos.delete({
              owner: user.login,
              repo: repoName,
            });
            console.log('Deleted existing repository');
            // Wait a moment for deletion to complete
            await new Promise(resolve => setTimeout(resolve, 3000));
          } else {
            throw refError;
          }
        }
      } catch (getError) {
        if (getError.status !== 404) {
          throw getError;
        }
        // Repository doesn't exist, create it
      }
      
      const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description,
        private: false,
        auto_init: true,
        homepage: `https://${owner}.github.io/${repoName}`,
      });
      
      // Wait a moment for repository to be fully initialized
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Verify the repository is properly initialized
      let retries = 0;
      const maxRetries = 5;
      while (retries < maxRetries) {
        try {
          await octokit.rest.git.getRef({
            owner: user.login,
            repo: repoName,
            ref: 'heads/main',
          });
          console.log('Repository successfully initialized with main branch');
          break;
        } catch (refError) {
          if (refError.status === 404 && retries < maxRetries - 1) {
            console.log(`Main branch not ready yet, waiting... (attempt ${retries + 1}/${maxRetries})`);
            await new Promise(resolve => setTimeout(resolve, 2000));
            retries++;
          } else {
            throw refError;
          }
        }
      }
      
      return repo;
    } catch (error) {
      console.error('Error creating repository:', error);
      throw error;
    }
  }

/**
 * Upload files to repository using Contents API (more reliable)
 * @param {string} accessToken - GitHub access token
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @param {Object} files - Files to upload { path: content }
 * @param {string} message - Commit message
 */
async uploadFiles(accessToken, owner, repo, files, message = 'Deploy portfolio') {
    const octokit = new Octokit({ auth: accessToken });
  
    try {
      // Verify repository exists and is accessible
      await octokit.rest.repos.get({ owner, repo });
      console.log(`Repository verified: ${owner}/${repo}`);
    } catch (error) {
      console.error(`Repository verification failed: ${error.message}`);
      throw new Error(`Repository ${owner}/${repo} is not accessible. Please ensure it exists and you have proper permissions.`);
    }

    console.log(`Uploading ${Object.keys(files).length} files using Contents API...`);
    
    // Sort files to upload directories first (create parent directories before files)
    const sortedFiles = Object.entries(files).sort(([pathA], [pathB]) => {
      const depthA = pathA.split('/').length;
      const depthB = pathB.split('/').length;
      return depthA - depthB;
    });
    
    // Upload files one by one using the Contents API
    const uploadedFiles = [];
    for (const [filePath, content] of sortedFiles) {
      try {
        console.log(`Uploading file: ${filePath}`);
        
        // For workflow files, create the directory structure step by step
        if (filePath.startsWith('.github/workflows/')) {
          try {
            // Step 1: Create .github directory
            try {
              await octokit.rest.repos.getContent({
                owner,
                repo,
                path: '.github',
              });
              console.log('.github directory already exists');
            } catch (dirError) {
              if (dirError.status === 404) {
                await octokit.rest.repos.createOrUpdateFileContents({
                  owner,
                  repo,
                  path: '.github/.gitkeep',
                  message: 'Create .github directory',
                  content: Buffer.from('# GitHub directory').toString('base64'),
                });
                console.log('Created .github directory');
                await new Promise(resolve => setTimeout(resolve, 1000));
              }
            }

            // Step 2: Create workflows directory
            try {
              await octokit.rest.repos.getContent({
                owner,
                repo,
                path: '.github/workflows',
              });
              console.log('.github/workflows directory already exists');
            } catch (workflowDirError) {
              if (workflowDirError.status === 404) {
                await octokit.rest.repos.createOrUpdateFileContents({
                  owner,
                  repo,
                  path: '.github/workflows/.gitkeep',
                  message: 'Create workflows directory',
                  content: Buffer.from('# Workflows directory').toString('base64'),
                });
                console.log('Created .github/workflows directory');
                await new Promise(resolve => setTimeout(resolve, 1000));
              }
            }
          } catch (dirCreateError) {
            console.warn(`Could not create directory structure for ${filePath}:`, dirCreateError.message);
          }
        }
        
        // Check if file already exists to get its SHA for updating
        let existingFileSha = null;
        try {
          const { data: existingFile } = await octokit.rest.repos.getContent({
            owner,
            repo,
            path: filePath,
          });
          if (existingFile.sha) {
            existingFileSha = existingFile.sha;
            console.log(`File ${filePath} exists, will update`);
          }
        } catch (getError) {
          if (getError.status !== 404) {
            console.warn(`Error checking existing file ${filePath}:`, getError.message);
          }
          // File doesn't exist, will create new
        }

        const isBinary = this.isBinaryFile(filePath);
        const fileContent = isBinary ? content : Buffer.from(content, 'utf8').toString('base64');
        
        const uploadParams = {
          owner,
          repo,
          path: filePath,
          message: `Add ${filePath}`,
          content: fileContent,
        };

        if (existingFileSha) {
          uploadParams.sha = existingFileSha;
          uploadParams.message = `Update ${filePath}`;
        }

        const { data: result } = await octokit.rest.repos.createOrUpdateFileContents(uploadParams);
        uploadedFiles.push({ path: filePath, sha: result.content.sha });
        
        // Small delay to avoid rate limiting
        await new Promise(resolve => setTimeout(resolve, 200));
        
      } catch (error) {
        console.error(`Failed to upload file ${filePath}:`, error.message);
        
        // If it's a workflow file and fails, skip it but continue with other files
        if (filePath.startsWith('.github/workflows/')) {
          console.log(`Attempting alternative upload for workflow file: ${filePath}`);
          try {
            // Try to create the file without checking for existing content
            const isBinary = this.isBinaryFile(filePath);
            const fileContent = isBinary ? content : Buffer.from(content, 'utf8').toString('base64');
            
            const { data: result } = await octokit.rest.repos.createOrUpdateFileContents({
              owner,
              repo,
              path: filePath,
              message: `Add GitHub Actions workflow`,
              content: fileContent,
            });
            
            uploadedFiles.push({ path: filePath, sha: result.content.sha });
            console.log(`Successfully uploaded workflow file: ${filePath}`);
            continue;
          } catch (altError) {
            console.error(`Alternative upload also failed for ${filePath}:`, altError.message);
            console.warn(`Skipping workflow file ${filePath} - deployment will continue without GitHub Actions`);
            continue; // Skip this file and continue with others
          }
        }
        
        throw new Error(`Failed to upload ${filePath}: ${error.message}`);
      }
    }

    console.log(`Successfully uploaded ${uploadedFiles.length} files`);
    
    // Create a final commit with all changes
    try {
      // Get the latest commit to use as parent
      const { data: ref } = await octokit.rest.git.getRef({
        owner,
        repo,
        ref: 'heads/main',
      });
      
      console.log(`All files uploaded successfully to ${owner}/${repo}`);
      return { sha: ref.object.sha, uploadedFiles };
      
    } catch (error) {
      console.warn('Could not get final commit SHA, but files were uploaded successfully');
      return { uploadedFiles };
    }
  }
  /**
   * Enable GitHub Pages for repository with GitHub Actions
   * @param {string} accessToken - GitHub access token
   * @param {string} owner - Repository owner
   * @param {string} repo - Repository name
   */
  async enableGitHubPages(accessToken, owner, repo) {
    const octokit = new Octokit({ auth: accessToken });

    try {
      // Try to create Pages site with GitHub Actions as source
      await octokit.rest.repos.createPagesSite({
        owner,
        repo,
        source: {
          branch: 'main',
          path: '/',
        },
      });
      console.log('GitHub Pages enabled with main branch source');
      
      // Update to use GitHub Actions for deployment
      try {
        await octokit.rest.repos.updateInformationAboutPagesSite({
          owner,
          repo,
          source: 'gh-actions',
        });
        console.log('GitHub Pages updated to use GitHub Actions');
      } catch (updateError) {
        console.warn('Could not update Pages to use GitHub Actions, but Pages is enabled:', updateError.message);
      }
      
    } catch (error) {
      if (error.status === 409) {
        // Pages already enabled, try to update it to use GitHub Actions
        console.log('GitHub Pages already enabled, updating to use GitHub Actions');
        try {
          await octokit.rest.repos.updateInformationAboutPagesSite({
            owner,
            repo,
            source: 'gh-actions',
          });
          console.log('GitHub Pages updated to use GitHub Actions');
        } catch (updateError) {
          console.warn('Could not update existing Pages to use GitHub Actions:', updateError.message);
        }
      } else {
        throw error;
      }
    }
  }

  /**
   * Generate GitHub Actions workflow for deployment
   * @param {string} template - Template name
   * @returns {string} Workflow YAML content
   */
  generateWorkflowYaml(template) {
    return `name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Build
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4`;
  }

  /**
   * Deploy portfolio to GitHub repository
   * @param {string} accessToken - GitHub access token
   * @param {Object} userData - User portfolio data
   * @param {string} template - Template name
   * @param {string} repoName - Repository name
   * @returns {Promise<Object>} Deployment result
   */
  async deployPortfolio(accessToken, userData, template, repoName) {
    console.log('Starting GitHub deployment...');
    
    // Get user info
    const user = await this.getUserInfo(accessToken);
    console.log(`Deploying for user: ${user.login}`);
    
    // Create repository
    const repo = await this.createRepository(accessToken, repoName);
    console.log(`Repository created/found: ${repo.full_name}`);
    
    // Get template files
    const templateFiles = await this.getTemplateFiles(template, userData);
    console.log(`Template files prepared: ${Object.keys(templateFiles).length} files`);
    
    // Add GitHub Actions workflow for dependency installation and building
    templateFiles['.github/workflows/deploy.yml'] = this.generateWorkflowYaml(template);
    
    console.log(`Template files with workflow: ${Object.keys(templateFiles).length} files`);
    
    // Upload files to repository (including workflow)
    const uploadResult = await this.uploadFiles(accessToken, user.login, repoName, templateFiles);
    console.log('Files uploaded to repository');
    
    // Enable GitHub Pages
    await this.enableGitHubPages(accessToken, user.login, repoName);
    console.log('GitHub Pages enabled');
    
    // Check if workflow was uploaded successfully
    const workflowUploaded = uploadResult.uploadedFiles?.some(file => 
      file.path === '.github/workflows/deploy.yml'
    );

    return {
      success: true,
      repository: repo,
      user: user,
      pagesUrl: `https://${user.login}.github.io/${repoName}`,
      workflowUploaded,
      manualWorkflowInstructions: !workflowUploaded ? {
        message: "GitHub Actions workflow needs to be added manually for automatic builds",
        steps: [
          "1. Go to your repository on GitHub",
          "2. Click 'Actions' tab",
          "3. Click 'New workflow' or 'set up a workflow yourself'",
          "4. Replace the default content with the provided workflow YAML",
          "5. Commit the file as '.github/workflows/deploy.yml'"
        ],
        workflowContent: this.generateWorkflowYaml(template)
      } : null
    };
  }

  /**
   * Get template files with user data injected
   * @param {string} template - Template name
   * @param {Object} userData - User portfolio data
   * @returns {Promise<Object>} Files object with path: content mapping
   */
  async getTemplateFiles(template, userData) {
    const templateDir = this.getTemplateDirectory(template);
    const files = {};
    
    // Read all files from template directory
    await this.readDirectoryRecursive(templateDir, templateDir, files);
    
    // Inject user data into specific files
    await this.injectUserDataIntoFiles(files, userData);
    
    return files;
  }

  /**
   * Get template directory path
   * @param {string} template - Template name
   * @returns {string} Template directory path
   */
  getTemplateDirectory(template) {
    const templatesBaseDir = path.join(__dirname, '../../templates');
    const templateMap = {
      'default': path.join(templatesBaseDir, 'react-portfolio'),
      'space': path.join(templatesBaseDir, 'space-portfolio'),
      'office': path.join(templatesBaseDir, 'office-portfolio'),
      'forest': path.join(templatesBaseDir, 'forest-portfolio'),
      'cave': path.join(templatesBaseDir, 'cave-portfolio'),
      'lab': path.join(templatesBaseDir, 'lab-portfolio')
    };
    return templateMap[template] || templateMap['default'];
  }
/**
 * Read directory recursively and build files object
 * @param {string} dir - Directory to read
 * @param {string} baseDir - Base directory for relative paths
 * @param {Object} files - Files object to populate
 */
async readDirectoryRecursive(dir, baseDir, files) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    
    for (const entry of entries) {
      if (entry.name.startsWith('.') || ['node_modules', '.git', 'dist', 'build', '.next', 'coverage'].includes(entry.name)) {
        continue; // Skip hidden/system files and unnecessary directories
      }
      const fullPath = path.join(dir, entry.name);
      const relativePath = path.relative(baseDir, fullPath).replace(/\\/g, '/');
      
      if (entry.isDirectory()) {
        await this.readDirectoryRecursive(fullPath, baseDir, files);
      } else {
        try {
          const content = await fs.readFile(fullPath);
          if (this.isBinaryFile(entry.name)) {
            files[relativePath] = content.toString('base64');
          } else {
            files[relativePath] = content.toString('utf8');
          }
        } catch (error) {
          console.warn(`Skipping file ${fullPath}: ${error.message}`);
        }
      }
    }
  }

/**
 * Check if file is binary
 * @param {string} filename - File name
 * @returns {boolean} True if binary file
 */
isBinaryFile(filename) {
    const binaryExtensions = [
      '.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', 
      '.woff', '.woff2', '.ttf', '.eot', '.bin', '.gltf', '.otf', '.glb'
    ];
    const ext = path.extname(filename).toLowerCase();
    return binaryExtensions.includes(ext);
  }

  /**
   * Inject user data into template files
   * @param {Object} files - Files object
   * @param {Object} userData - User portfolio data
   */
  async injectUserDataIntoFiles(files, userData) {
    // Update package.json
    if (files['package.json']) {
      const packageJson = JSON.parse(files['package.json']);
      packageJson.name = userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website';
      packageJson.homepage = `https://${userData.githubUsername || 'username'}.github.io/${packageJson.name}`;
      files['package.json'] = JSON.stringify(packageJson, null, 2);
    }

    // Update index.html
    if (files['public/index.html']) {
      files['public/index.html'] = files['public/index.html']
        .replace(/{{USER_NAME}}/g, userData.name || 'Portfolio User');
    }

    // Update README.md
    if (files['README.md']) {
      files['README.md'] = files['README.md']
        .replace(/{{USER_NAME}}/g, userData.name || 'Portfolio User')
        .replace(/{{REPO_NAME}}/g, userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website');
    }

    // Update portfolio data
    if (files['src/data/portfolioData.js']) {
      files['src/data/portfolioData.js'] = files['src/data/portfolioData.js']
        .replace(/{{USER_NAME}}/g, userData.name || 'Portfolio User')
        .replace(/{{USER_TITLE}}/g, userData.title || 'Professional')
        .replace(/{{USER_SUMMARY}}/g, userData.summary || '')
        .replace(/{{USER_SKILLS}}/g, JSON.stringify(userData.skills || []))
        .replace(/{{USER_EXPERIENCE}}/g, JSON.stringify(userData.experience || []))
        .replace(/{{USER_EDUCATION}}/g, JSON.stringify(userData.education || []))
        .replace(/{{USER_PROJECTS}}/g, JSON.stringify(userData.projects || []))
        .replace(/{{USER_EMAIL}}/g, userData.contact?.email || '')
        .replace(/{{USER_PHONE}}/g, userData.contact?.phone || '')
        .replace(/{{USER_LINKEDIN}}/g, userData.contact?.linkedin || '')
        .replace(/{{USER_GITHUB}}/g, userData.contact?.github || '');
    }

    // Fix asset paths for GitHub Pages deployment
    const repoName = userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website';
    
    // Update 3D model paths in Office component
    if (files['src/components/3DModels/Office.jsx']) {
      files['src/components/3DModels/Office.jsx'] = files['src/components/3DModels/Office.jsx']
        .replace(/useGLTF\('\/office\/office\.gltf'\)/g, `useGLTF(process.env.PUBLIC_URL + '/office/office.gltf')`)
        .replace(/useGLTF\.preload\('\/office\/office\.gltf'\)/g, `useGLTF.preload(process.env.PUBLIC_URL + '/office/office.gltf')`);
    }

    // Update other 3D model components if they exist
    Object.keys(files).forEach(filePath => {
      if (filePath.includes('3DModels') && (filePath.endsWith('.js') || filePath.endsWith('.jsx'))) {
        // Fix absolute paths to 3D models and other assets
        files[filePath] = files[filePath]
          .replace(/useGLTF\('\/([^']+)'\)/g, `useGLTF(process.env.PUBLIC_URL + '/$1')`)
          .replace(/useGLTF\.preload\('\/([^']+)'\)/g, `useGLTF.preload(process.env.PUBLIC_URL + '/$1')`);
      }
    });

    // Don't add Vite config if template already uses react-scripts
    // Only add Vite config for templates that actually use Vite
    if (!files['package.json'] || !files['package.json'].includes('react-scripts')) {
      files['vite.config.js'] = this.generateViteConfig(userData);
    }
  }

  /**
   * Generate Vite configuration for GitHub Pages
   * @param {Object} userData - User data
   * @returns {string} Vite config content
   */
  generateViteConfig(userData) {
    const repoName = userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website';
    
    return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: process.env.NODE_ENV === 'production' ? '/${repoName}/' : '/',
  build: {
    outDir: 'dist',
  },
})`;
  }
}

module.exports = new GitHubService();