// server/services/github.service.js

const { Octokit } = require('@octokit/rest');
const fs = require('fs').promises;
const path = require('path');
const archiver = require('archiver');

class GitHubService {
  constructor() {
    this.clientId = process.env.GITHUB_CLIENT_ID;
    this.clientSecret = process.env.GITHUB_CLIENT_SECRET;
    this.redirectUri = process.env.GITHUB_REDIRECT_URI;
  }

  /**
   * Generate GitHub OAuth authorization URL
   * @param {string} state - State parameter for security
   * @returns {string} Authorization URL
   */
  getAuthUrl(state) {
    const scopes = 'repo,user:email';
    return `https://github.com/login/oauth/authorize?client_id=${this.clientId}&redirect_uri=${encodeURIComponent(this.redirectUri)}&scope=${scopes}&state=${state}`;
  }

  /**
   * Exchange authorization code for access token
   * @param {string} code - Authorization code from GitHub
   * @returns {Promise<string>} Access token
   */
  async getAccessToken(code) {
    const response = await fetch('https://github.com/login/oauth/access_token', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        client_id: this.clientId,
        client_secret: this.clientSecret,
        code,
        redirect_uri: this.redirectUri,
      }),
    });

    const data = await response.json();
    
    if (data.error) {
      throw new Error(`GitHub OAuth error: ${data.error_description}`);
    }

    return data.access_token;
  }

  /**
   * Get GitHub user information
   * @param {string} accessToken - GitHub access token
   * @returns {Promise<Object>} User information
   */
  async getUserInfo(accessToken) {
    const octokit = new Octokit({ auth: accessToken });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    return user;
  }

  /**
   * Create a new repository for the user
   * @param {string} accessToken - GitHub access token
   * @param {string} repoName - Repository name
   * @param {string} description - Repository description
   * @returns {Promise<Object>} Repository information
   */
  async createRepository(accessToken, repoName, description = 'Portfolio website generated by Portfolio Portal') {
    const octokit = new Octokit({ auth: accessToken });
    
    try {
      const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description,
        private: false,
        auto_init: true,
        homepage: `https://${repoName}.github.io/${repoName}`,
      });

      return repo;
    } catch (error) {
      if (error.status === 422) {
        // Repository already exists, try to get it
        const { data: user } = await octokit.rest.users.getAuthenticated();
        const { data: repo } = await octokit.rest.repos.get({
          owner: user.login,
          repo: repoName,
        });
        return repo;
      }
      throw error;
    }
  }

  /**
   * Upload files to repository
   * @param {string} accessToken - GitHub access token
   * @param {string} owner - Repository owner
   * @param {string} repo - Repository name
   * @param {Object} files - Files to upload { path: content }
   * @param {string} message - Commit message
   */
  async uploadFiles(accessToken, owner, repo, files, message = 'Deploy portfolio') {
    const octokit = new Octokit({ auth: accessToken });

    // Get the latest commit SHA
    const { data: ref } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: 'heads/main',
    });

    const { data: commit } = await octokit.rest.git.getCommit({
      owner,
      repo,
      commit_sha: ref.object.sha,
    });

    // Create blobs for all files
    const blobs = [];
    for (const [filePath, content] of Object.entries(files)) {
      const { data: blob } = await octokit.rest.git.createBlob({
        owner,
        repo,
        content: Buffer.from(content).toString('base64'),
        encoding: 'base64',
      });
      
      blobs.push({
        path: filePath,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      });
    }

    // Create new tree
    const { data: tree } = await octokit.rest.git.createTree({
      owner,
      repo,
      base_tree: commit.tree.sha,
      tree: blobs,
    });

    // Create new commit
    const { data: newCommit } = await octokit.rest.git.createCommit({
      owner,
      repo,
      message,
      tree: tree.sha,
      parents: [commit.sha],
    });

    // Update reference
    await octokit.rest.git.updateRef({
      owner,
      repo,
      ref: 'heads/main',
      sha: newCommit.sha,
    });

    return newCommit;
  }

  /**
   * Enable GitHub Pages for repository
   * @param {string} accessToken - GitHub access token
   * @param {string} owner - Repository owner
   * @param {string} repo - Repository name
   */
  async enableGitHubPages(accessToken, owner, repo) {
    const octokit = new Octokit({ auth: accessToken });

    try {
      await octokit.rest.repos.createPagesSite({
        owner,
        repo,
        source: {
          branch: 'main',
          path: '/',
        },
      });
    } catch (error) {
      if (error.status === 409) {
        // Pages already enabled
        console.log('GitHub Pages already enabled for repository');
        return;
      }
      throw error;
    }
  }

  /**
   * Generate GitHub Actions workflow for deployment
   * @param {string} template - Template name
   * @returns {string} Workflow YAML content
   */
  generateWorkflowYaml(template) {
    return `name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4`;
  }

  /**
   * Deploy portfolio to GitHub repository
   * @param {string} accessToken - GitHub access token
   * @param {Object} userData - User portfolio data
   * @param {string} template - Template name
   * @param {string} repoName - Repository name
   * @returns {Promise<Object>} Deployment result
   */
  async deployPortfolio(accessToken, userData, template, repoName) {
    console.log('Starting GitHub deployment...');
    
    // Get user info
    const user = await this.getUserInfo(accessToken);
    console.log(`Deploying for user: ${user.login}`);
    
    // Create repository
    const repo = await this.createRepository(accessToken, repoName);
    console.log(`Repository created/found: ${repo.full_name}`);
    
    // Get template files
    const templateFiles = await this.getTemplateFiles(template, userData);
    console.log(`Template files prepared: ${Object.keys(templateFiles).length} files`);
    
    // Add GitHub Actions workflow
    templateFiles['.github/workflows/deploy.yml'] = this.generateWorkflowYaml(template);
    
    // Upload files to repository
    await this.uploadFiles(accessToken, user.login, repoName, templateFiles);
    console.log('Files uploaded to repository');
    
    // Enable GitHub Pages
    await this.enableGitHubPages(accessToken, user.login, repoName);
    console.log('GitHub Pages enabled');
    
    return {
      success: true,
      repository: repo,
      user: user,
      pagesUrl: `https://${user.login}.github.io/${repoName}`,
    };
  }

  /**
   * Get template files with user data injected
   * @param {string} template - Template name
   * @param {Object} userData - User portfolio data
   * @returns {Promise<Object>} Files object with path: content mapping
   */
  async getTemplateFiles(template, userData) {
    const templateDir = this.getTemplateDirectory(template);
    const files = {};
    
    // Read all files from template directory
    await this.readDirectoryRecursive(templateDir, templateDir, files);
    
    // Inject user data into specific files
    await this.injectUserDataIntoFiles(files, userData);
    
    return files;
  }

  /**
   * Get template directory path
   * @param {string} template - Template name
   * @returns {string} Template directory path
   */
  getTemplateDirectory(template) {
    const templatesBaseDir = path.join(__dirname, '../../templates');
    const templateMap = {
      'default': path.join(templatesBaseDir, 'react-portfolio'),
      'space': path.join(templatesBaseDir, 'space-portfolio'),
      'office': path.join(templatesBaseDir, 'office-portfolio'),
      'forest': path.join(templatesBaseDir, 'forest-portfolio'),
      'cave': path.join(templatesBaseDir, 'cave-portfolio'),
      'lab': path.join(templatesBaseDir, 'lab-portfolio')
    };
    return templateMap[template] || templateMap['default'];
  }

  /**
   * Read directory recursively and build files object
   * @param {string} dir - Directory to read
   * @param {string} baseDir - Base directory for relative paths
   * @param {Object} files - Files object to populate
   */
  async readDirectoryRecursive(dir, baseDir, files) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relativePath = path.relative(baseDir, fullPath).replace(/\\/g, '/');
      
      if (entry.isDirectory()) {
        // Skip unnecessary directories
        if (['node_modules', '.git', 'dist', 'build', '.next', 'coverage'].includes(entry.name)) {
          continue;
        }
        await this.readDirectoryRecursive(fullPath, baseDir, files);
      } else {
        try {
          // Check if file is binary or text
          const content = await fs.readFile(fullPath);
          
          // For binary files (images, etc.), convert to base64
          if (this.isBinaryFile(entry.name)) {
            files[relativePath] = content.toString('base64');
          } else {
            files[relativePath] = content.toString('utf8');
          }
        } catch (error) {
          console.warn(`Skipping file ${fullPath}: ${error.message}`);
        }
      }
    }
  }

  /**
   * Check if file is binary
   * @param {string} filename - File name
   * @returns {boolean} True if binary file
   */
  isBinaryFile(filename) {
    const binaryExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', '.woff', '.woff2', '.ttf', '.eot'];
    const ext = path.extname(filename).toLowerCase();
    return binaryExtensions.includes(ext);
  }

  /**
   * Inject user data into template files
   * @param {Object} files - Files object
   * @param {Object} userData - User portfolio data
   */
  async injectUserDataIntoFiles(files, userData) {
    // Update package.json
    if (files['package.json']) {
      const packageJson = JSON.parse(files['package.json']);
      packageJson.name = userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website';
      packageJson.homepage = `https://${userData.githubUsername || 'username'}.github.io/${packageJson.name}`;
      files['package.json'] = JSON.stringify(packageJson, null, 2);
    }

    // Update index.html
    if (files['public/index.html']) {
      files['public/index.html'] = files['public/index.html']
        .replace(/{{USER_NAME}}/g, userData.name || 'Portfolio User');
    }

    // Update README.md
    if (files['README.md']) {
      files['README.md'] = files['README.md']
        .replace(/{{USER_NAME}}/g, userData.name || 'Portfolio User')
        .replace(/{{REPO_NAME}}/g, userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website');
    }

    // Update portfolio data
    if (files['src/data/portfolioData.js']) {
      files['src/data/portfolioData.js'] = files['src/data/portfolioData.js']
        .replace(/{{USER_NAME}}/g, userData.name || 'Portfolio User')
        .replace(/{{USER_TITLE}}/g, userData.title || 'Professional')
        .replace(/{{USER_SUMMARY}}/g, userData.summary || '')
        .replace(/{{USER_SKILLS}}/g, JSON.stringify(userData.skills || []))
        .replace(/{{USER_EXPERIENCE}}/g, JSON.stringify(userData.experience || []))
        .replace(/{{USER_EDUCATION}}/g, JSON.stringify(userData.education || []))
        .replace(/{{USER_PROJECTS}}/g, JSON.stringify(userData.projects || []))
        .replace(/{{USER_EMAIL}}/g, userData.contact?.email || '')
        .replace(/{{USER_PHONE}}/g, userData.contact?.phone || '')
        .replace(/{{USER_LINKEDIN}}/g, userData.contact?.linkedin || '')
        .replace(/{{USER_GITHUB}}/g, userData.contact?.github || '');
    }

    // Add Vite config for GitHub Pages deployment
    files['vite.config.js'] = this.generateViteConfig(userData);
  }

  /**
   * Generate Vite configuration for GitHub Pages
   * @param {Object} userData - User data
   * @returns {string} Vite config content
   */
  generateViteConfig(userData) {
    const repoName = userData.name ? userData.name.toLowerCase().replace(/\s+/g, '-') + '-portfolio' : 'portfolio-website';
    
    return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: process.env.NODE_ENV === 'production' ? '/${repoName}/' : '/',
  build: {
    outDir: 'dist',
  },
})`;
  }
}

module.exports = new GitHubService();