/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 campfire.gltf 
Author: Mandrake (https://sketchfab.com/mandrake_3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/campfire-1f6834effb514d4c8a0fd34accb88251
Title: Campfire
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/campfire/campfire.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wooden_logs_campfire_set_0.geometry} material={materials.campfire_set} position={[-181.787, 218.066, 1.422]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.wooden_log_top_campfire_set_0.geometry} material={materials.campfire_set} position={[-3.223, 236.642, 1.422]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ropes_campfire_set_0.geometry} material={materials.campfire_set} position={[-178.355, 227.782, 0.228]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.kauchi_campfire_set_0.geometry} material={materials.campfire_set} position={[-2.875, 218.519, 1.422]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.kettle_campfire_set_0.geometry} material={materials.campfire_set} position={[23.625, 90.547, -3.662]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.burnt_logs_campfire_set_0.geometry} material={materials.campfire_set} position={[-2.731, 10.487, -0.856]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.nashshiri_campfire_set_0.geometry} material={materials.campfire_set} position={[0.724, 0, -16.27]} rotation={[-Math.PI / 2, 0, 0]} scale={62.84} />
      <mesh geometry={nodes.rock015_rock_0.geometry} material={materials.rock} position={[-0.288, 2.727, -14.298]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/campfire/campfire.gltf')
