/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 crystal.gltf 
Author: Ethan C (https://sketchfab.com/EthanfromEngland)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stalagmitecrystalore-cluster-meshy-258853e602dc437a94757da529c0f745
Title: Stalagmite/Crystal/Ore Cluster - [MESHY]
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/crystals/crystal.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.temp_Material001_0.geometry} material={materials['Material.001']} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/crystals/crystal.gltf')
