/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dinoskeleton.gltf 
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coelophysis-bauri-81st-street-ny-subway-1960191653da4987bce289e183d777f4
Title: Coelophysis bauri - 81st Street NY Subway
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/dinoskeleton/dinoskeleton.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Coelophysis_bauri} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Coelophysis_bauri} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Coelophysis_bauri} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/dinoskeleton/dinoskeleton.gltf')
