/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 floatingCrystal.gltf 
Author: ARTEL_3D (https://sketchfab.com/artel_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mystic-crystal-artifact-4d8156fb54a14e2e8afe0b68e7a7a191
Title: Mystic Crystal Artifact
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('floatingcrystal/floatingCrystal.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.103}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('floatingCrystal/floatingCrystal.gltf')
