/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 graduation.gltf 
Author: Delo (https://sketchfab.com/DevFaisal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/graduation-hat-b0a7e821403b4c8cb8e1d32ea4075eac
Title: Graduation Hat
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/graduation_hat/graduation.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -2.644]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 12.406]}>
            <mesh geometry={nodes.Cube_book_0.geometry} material={materials.book} />
            <mesh geometry={nodes.Cube_pages_0.geometry} material={materials.pages} />
          </group>
          <group position={[0, 25.101, 0]} rotation={[-Math.PI / 2, 0, 0.686]} scale={[100, 100, 12.406]}>
            <mesh geometry={nodes.Cube001_book_2__0.geometry} material={materials.book_2} />
            <mesh geometry={nodes.Cube001_pages_0.geometry} material={materials.pages} />
          </group>
          <group position={[-75.693, 67.395, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={3.59}>
            <mesh geometry={nodes.Sphere_bood_0.geometry} material={materials.bood} />
            <mesh geometry={nodes.Sphere_roope_0.geometry} material={materials.roope} />
          </group>
          <mesh geometry={nodes.Torus_hat_0.geometry} material={materials.material} position={[0, 42.25, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/graduation_hat/graduation.gltf')
