/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pickaxe.gltf 
Author: Horus Chen (https://sketchfab.com/horuschen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pickaxe-g-4bc5524e005344b5b7ed0efb494ba600
Title: Pickaxe-G
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pickaxe/pickaxe.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Pick_Axe} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/pickaxe/pickaxe.gltf')
