/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plane.gltf 
Author: Josh Galeto (https://sketchfab.com/JoshGaleto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planes-of-the-head-andrew-loomis-method-19424b7aa2fc4a4d8987efe4bdb62395
Title: Planes of the Head - Andrew Loomis Method
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/plane-heads/plane.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[193.188, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Face02_heads_0.geometry} material={materials.heads} />
            <mesh geometry={nodes.Face02_heads_Outline_0.geometry} material={materials.heads_Outline} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Face01_heads_0.geometry} material={materials.heads} />
            <mesh geometry={nodes.Face01_heads_Outline_0.geometry} material={materials.heads_Outline} />
          </group>
          <group position={[384.51, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Face03_heads_0.geometry} material={materials.heads} />
            <mesh geometry={nodes.Face03_heads_Outline_0.geometry} material={materials.heads_Outline} />
          </group>
          <group position={[575.153, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Face04_heads_0.geometry} material={materials.heads} />
            <mesh geometry={nodes.Face04_heads_Outline_0.geometry} material={materials.heads_Outline} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['3001_00Linhas_0'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['3001_00Linhas_0_1'].geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['1001_00Linhas_0'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['1001_00Linhas_0_1'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['1001_00Linhas_0_2'].geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['4001_00Linhas_0'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['4001_00Linhas_0_1'].geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['2001_00Linhas_0'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['2001_00Linhas_0_1'].geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['02_00Linhas_0'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['02_00Linhas_0_1'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['02_00Linhas_0_2'].geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes['02_00Linhas_0_3'].geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.facefeatures001_00Linhas_0.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.facefeatures001_00Linhas_0_1.geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.head_00Linhas_0.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.head_00Linhas_0_1.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.head_00Linhas_0_2.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.head_00Linhas_0_3.geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.facefeatures_00Linhas_0.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.facefeatures_00Linhas_0_1.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.facefeatures_00Linhas_0_2.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.facefeatures_00Linhas_0_3.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.facefeatures_00Linhas_0_4.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.facefeatures_00Linhas_0_5.geometry} material={materials['00Linhas']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.headfeatures_00Linhas_0.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.headfeatures_00Linhas_0_1.geometry} material={materials['00Linhas']} />
            <mesh geometry={nodes.headfeatures_00Linhas_0_2.geometry} material={materials['00Linhas']} />
          </group>
          <mesh geometry={nodes.Eyes__0.geometry} material={materials.Eyes__0} position={[606, -12.995, 61.412]} rotation={[-Math.PI / 2, 0, 0]} scale={1.47} />
          <mesh geometry={nodes['1_00Linhas_0'].geometry} material={materials['00Linhas']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['2_00Linhas_0'].geometry} material={materials['00Linhas']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['3_00Linhas_0'].geometry} material={materials['00Linhas']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['4_00Linhas_0'].geometry} material={materials['00Linhas']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plane-heads/plane.gltf')
