/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shovel.gltf 
Author: Rzyas (https://sketchfab.com/rzyas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shovel-a2f03b43600e40a5a58474039407f648
Title: Shovel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shovel/shovel.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Sekop_Pasir_Sekop_Pasir_MAT_0.geometry} material={materials.Sekop_Pasir_MAT} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/shovel/shovel.gltf')
