[phases.setup]
nixPkgs = ["nodejs_20", "graphicsmagick", "ghostscript", "poppler_utils", "tesseract"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "node server.js"